#ifndef _IMF_PARSE_ERROR_H_
#define _IMF_PARSE_ERROR_H_


#define ERR_IMFPARSER_INIT_FAIL (0x10000)

#define ERROR_PARSE_BOX_FTYPE   (0x20000)
#define ERROR_PARSE_TRAK_HDR    (0x20001)
#define ERROR_PARSE_MOVIE_HDR   (0x20002)
#endif


